const initial={tournaments:JSON.parse(localStorage.getItem('spin-tournaments')||'[]')};let state={view:location.hash.slice(1)||'home',...initial};
const save=()=>localStorage.setItem('spin-tournaments',JSON.stringify(state.tournaments));
const app=document.querySelector('#app');
function layout(content){app.innerHTML=`<section class="view">${content}</section>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view))}
function go(view){state.view=view;location.hash=view;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render()}
function render(){if(state.view==='scoreboard')return scoreboard();if(state.view==='schedule')return schedule();if(state.view==='manage')return manage();home()}
function home(){layout(`<div class="hero"><div><div class="eyebrow">THE ARENA STARTS HERE</div><h1>SPIN<br><span>LEAGUE</span></h1><p class="lead">讓每一場對戰都清楚、快速、好玩。從臨時記分到正式淘汰賽，一個畫面掌握整個賽事。</p><div class="actions"><button class="btn primary" data-view="manage">建立新賽事</button><button class="btn ghost" data-view="scoreboard">開啟記分板</button></div></div><div class="gyro-art"></div></div><div class="section-head"><div><h2>開始你的比賽</h2><p class="sub">選擇一個工具開始使用</p></div></div><div class="cards"><div class="card" data-view="scoreboard"><span class="icon">⏱</span><h3>獨立記分板</h3><p>適合練習與臨時對戰，不會影響正式賽事紀錄。</p></div><div class="card" data-view="schedule"><span class="icon">⌘</span><h3>賽程表</h3><p>查看淘汰賽樹狀圖、比賽狀態與晉級結果。</p></div><div class="card" data-view="manage"><span class="icon">✦</span><h3>賽事管理</h3><p>建立賽事、輸入選手，立即產生單淘汰賽程。</p></div></div>`);document.querySelectorAll('.card,.actions [data-view]').forEach(x=>x.onclick=()=>go(x.dataset.view))}
function scoreboard(){layout(`<div class="section-head"><div><div class="eyebrow">QUICK MATCH</div><h2>獨立記分板</h2><p class="sub">此比分不會連動任何正式賽事。</p></div><button class="btn ghost" id="reset">重設比分</button></div><div class="score-grid"><div class="score-box"><input value="選手 A" aria-label="左方選手名稱"><div class="score" id="a">0</div><button class="btn" data-score="a" data-add="1">＋ 1</button><button class="btn" data-score="a" data-add="-1">− 1</button></div><div class="score-box red"><input value="選手 B" aria-label="右方選手名稱"><div class="score" id="b">0</div><button class="btn" data-score="b" data-add="1">＋ 1</button><button class="btn" data-score="b" data-add="-1">− 1</button></div></div>`);let s={a:0,b:0};document.querySelectorAll('[data-score]').forEach(x=>x.onclick=()=>{s[x.dataset.score]=Math.max(0,s[x.dataset.score]+Number(x.dataset.add));document.querySelector('#'+x.dataset.score).textContent=s[x.dataset.score]});document.querySelector('#reset').onclick=()=>{if(confirm('確定重設比分？')){s={a:0,b:0};document.querySelector('#a').textContent=0;document.querySelector('#b').textContent=0}}}
function manage(){layout(`<div class="section-head"><div><div class="eyebrow">TOURNAMENT SETUP</div><h2>建立新賽事</h2><p class="sub">目前支援單淘汰賽，最多先建立 16 位選手。</p></div></div><div class="panel"><div class="field"><label>賽事名稱</label><input id="tname" placeholder="例如：夏季公開賽"></div><div class="field"><label>參賽者名單（一行一位）</label><textarea id="players" placeholder="小明\n阿龍\nSpin Master\n..."></textarea></div><button class="btn primary" id="create">產生賽程</button></div>`);document.querySelector('#create').onclick=()=>{const name=document.querySelector('#tname').value.trim()||'未命名賽事';const players=document.querySelector('#players').value.split('\n').map(x=>x.trim()).filter(Boolean);if(players.length<2)return alert('請至少輸入 2 位參賽者');state.tournaments.unshift({id:Date.now(),name,players,created:new Date().toLocaleDateString('zh-TW')});save();go('schedule')}}
function schedule(){const list=state.tournaments.map(t=>`<div class="card" data-id="${t.id}"><h3>${t.name}</h3><p>${t.players.length} 位參賽者 · 建立於 ${t.created}</p><button class="btn ghost">查看賽程</button></div>`).join('');layout(`<div class="section-head"><div><div class="eyebrow">TOURNAMENTS</div><h2>賽程表</h2><p class="sub">選擇一場賽事查看對戰樹狀圖。</p></div><button class="btn primary" data-view="manage">＋ 新賽事</button></div>${list?`<div class="cards">${list}</div>`:'<div class="notice">目前還沒有正式賽事，先建立第一場吧。</div>'}`);document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>bracket(Number(x.dataset.id)));document.querySelector('[data-view="manage"]')?.addEventListener('click',()=>go('manage'))}
function bracket(id){const t=state.tournaments.find(x=>x.id===id);const ps=[...t.players];while(ps.length<8)ps.push('輪空');const pairs=ps.slice(0,8).reduce((a,x,i)=>i%2?a:a.concat([[x,ps[i+1]]]),[]);layout(`<div class="section-head"><div><div class="eyebrow">LIVE BRACKET</div><h2>${t.name}</h2><p class="sub">單淘汰賽 · ${t.players.length} 位參賽者</p></div><button class="btn ghost" data-view="schedule">返回賽程表</button></div><div class="bracket"><div class="round"><h3>八強賽</h3>${pairs.map(p=>`<div class="match"><div>${p[0]} <b>—</b></div><div>${p[1]} <b>—</b></div></div>`).join('')}</div><div class="round"><h3>準決賽</h3>${[1,2].map(()=>'<div class="match"><div>待定 <b>—</b></div><div>待定 <b>—</b></div></div>').join('')}</div><div class="round"><h3>冠軍賽</h3><div class="match"><div>待定 <b>—</b></div><div>待定 <b>—</b></div></div></div></div>`);document.querySelector('[data-view="schedule"]').onclick=()=>go('schedule')}
render();
