/** Stable Worker bridge to shared tournament rules; packaging rewrites only this import. */
export {
  MAX_TOURNAMENT_PLAYERS,
  addConfirmedParticipant,
  addDraftPlayer,
  confirmTournamentSchedule,
  drawRandomSeeds,
  forfeitMatch,
  prepareTournamentSchedule,
  randomizeDraftTournament,
  randomizeTournamentSchedule,
  recordMatchResult,
  removeDraftPlayer,
  resetCompletedMatch,
  completeSwissByStandings,
  completeTournamentEarly,
  setDraftPlayerCheckedIn,
  setAllDraftPlayersCheckedIn,
  startSwissFinal,
  startSwissQualifier,
  startRoundRobinTieBreak,
  startTournament,
  toPublicTournament,
  updateOpeningPairings,
  updateDraftParticipant,
  updateRegistrationSettings,
  withdrawPlayer,
} from '../src/domain/tournament.js';
